# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 191cdca5f0c8efbfa91e1aff997aae0c588352aa00d893fab72b082b6818615c228df3e5c7f7848c350297e7ea5a6a0450fac805c2d2242660d427dca3080853

test:
  secret_key_base: cbcd6aac2ada06f34de6e0f29f56b0f1ddfc564330ba84df1cd11082717c95280fb3544c13388e1c6500307a5159d502b6f31baade2eb8f1f461576db3e5ce32

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
